### PR TITLE
Convert alerts to styled components

### PR DESCRIPTION
**Pull request by Chochek**

### CODE REVIEW

**Comment by Chochek** [comment]
## Review plan
- [ ] Go to https://dev-react-ions.herokuapp.com/components/alerts
- [ ] Test out all alert examples
- [ ] They all work and alerts with timers now have a countdown bar that lets you know how long the alert will be displayed
- [ ] When you hover over an alert the countdown bar stops until you move your cursor away from the alert
- [ ] Tests were converted into jest and converage was improved
- [ ] Circle build passes - https://circleci.com/gh/GetAmbassador/react-ions/tree/convert_alerts_to_styled_components

**Comment by Chochek** [comment]
@gpszymczak please review

**Comment by gpszymczak** [comment]
reviewing

**Comment by gpszymczak** [comment]
👍 on review

**Pull request merged**
