### PR TITLE
Auto generate main index.js file

### PR DESCRIPTION
**Pull request by Chochek**

### CODE REVIEW

**Comment by Chochek** [comment]
**Review plan**

- [ ] Checkout this branch
- [ ] Delete the `lib` folder
- [ ] Run `npm run build:release`
- [ ] Confirm that there is a `lib/index.js` file with all the module exports
- [ ] Run the app locally
- [ ] Go to http://react.ions:3000/components/
- [ ] Click through all the components in the sidebar to make sure everything still works

**Comment by Chochek** [comment]
@samageloff please review when you have some free time. No rush

**Comment by samageloff** [comment]
@jivinivan if you can give this a review - great!

**Comment by samageloff** [comment]
bitmoji

**Comment by samageloff** [comment]
@jivinivan @Chochek you think we can get this out the door? This PR will make the upgrade path to Ions a little bit easier, as the import syntax will match.

**Pull request closed without merging**
