### PR TITLE
Allow a tagList component to be passed to the MultiSelect component

### PR DESCRIPTION
**Pull request by Chochek**

### CODE REVIEW

**Comment by Chochek** [comment]
## Review plan

- Go to http://react.ions:3000/components/multi-select
- At the bottom there's a `Multi Select Field with a customized list of selected items` example
- The new prop was added to the bottom od the list of props

**Comment by Chochek** [comment]
@gpszymczak please review ^

**Comment by gpszymczak** [comment]
reviewing

**Comment by gpszymczak** [comment]
👍 on review

**Pull request merged**
